// ---------------------------------------------------------------------------
// RESOURCE ARTICLES
// ---------------------------------------------------------------------------
// Full-length mentor-voice articles behind the "Resources & Insights"
// section. Each is rendered at /resources/[slug]. `body` is a small block
// system (paragraph / heading / subheading / list) rather than markdown, so
// every article renders through the same typographic system as the rest of
// the site — see components/ArticleBody.tsx.
// ---------------------------------------------------------------------------

export type ArticleBlock =
  | { type: "paragraph"; text: string; emphasis?: boolean }
  | { type: "heading"; text: string }
  | { type: "subheading"; text: string }
  | { type: "list"; items: string[] };

export type Article = {
  slug: string;
  category: string;
  title: string;
  excerpt: string;
  readingTime: string;
  body: ArticleBlock[];
};

const p = (text: string, emphasis?: boolean): ArticleBlock => ({
  type: "paragraph",
  text,
  ...(emphasis ? { emphasis: true } : {}),
});
const h = (text: string): ArticleBlock => ({ type: "heading", text });
const sub = (text: string): ArticleBlock => ({ type: "subheading", text });
const list = (items: string[]): ArticleBlock => ({ type: "list", items });

export const articles: Article[] = [
  {
    slug: "writing-score-stuck",
    category: "Writing",
    title: "Why Your IELTS Writing Score May Be Stuck",
    excerpt:
      "If your Writing score keeps landing in the same place, more essays might not be the fix — understanding why it's being scored that way is.",
    readingTime: "5–6 min",
    body: [
      p("You've written essays. You've practiced different question types. You've learned linking words, improved your vocabulary, and probably memorized a few structures."),
      p("Yet your Writing score still seems to sit in the same place."),
      p("Maybe you're getting 6.0 again and again. Or perhaps you've reached 6.5 but can't seem to move beyond it."),
      p("If that sounds familiar, the problem may not be that you need to write more."),
      p("You may need to understand why your writing is being scored the way it is.", true),

      h("More practice isn't always the answer"),
      p("One of the most common IELTS mistakes is responding to a disappointing writing score by simply writing another essay."),
      p("Then another."),
      p("And another."),
      p("But if you keep repeating the same weaknesses, more practice can simply make those weaknesses more familiar."),
      p("Improvement starts when you can identify the specific reason your writing isn't moving forward.", true),
      p("For IELTS Writing, four areas matter:"),
      list([
        "Task Response / Task Achievement",
        "Coherence and Cohesion",
        "Lexical Resource",
        "Grammatical Range and Accuracy",
      ]),
      p("Your score reflects your performance across these areas—not how impressive your essay looks at first glance."),

      h("You may be answering the question without fully answering it"),
      p("This is particularly common in Task 2."),
      p("You might have a clear opinion and several good ideas, but that doesn't necessarily mean you've fully addressed the task."),
      p("Ask yourself:"),
      p("“Have I answered every part of the question, or have I answered the question I wanted to answer?”", true),
      p("A strong essay needs relevant ideas, but relevance alone isn't enough."),
      p("Your ideas need to be developed, explained, and connected to the question."),
      p("Instead of writing:"),
      p("Technology has improved education because students can access information more easily.", true),
      p("Go one step further."),
      p("Why does easier access matter?"),
      p("How does it change learning?"),
      p("What is the consequence?"),
      p("That additional layer of explanation is often where an ordinary idea becomes a well-developed argument."),

      h("Better vocabulary isn't the same as bigger vocabulary"),
      p("Another common trap is believing that a higher band requires increasingly complicated words."),
      p("It doesn't."),
      p("Using an unfamiliar word incorrectly won't make your writing more sophisticated."),
      p("In fact, it can make your writing less precise."),
      p("The goal is not to demonstrate how many advanced words you know."),
      p("The goal is to express your ideas accurately, naturally, and appropriately."),
      p("A simple word used precisely is usually more valuable than an impressive word used awkwardly.", true),

      h("Your grammar may be limiting you more than you realize"),
      p("You don't need perfect grammar to achieve a strong IELTS score."),
      p("But if the same grammatical problems appear repeatedly, they can become a ceiling."),
      p("Look at your writing and ask:"),
      list([
        "Do I make the same errors with articles?",
        "Do I confuse singular and plural forms?",
        "Are my complex sentences actually clear?",
        "Do I rely on the same sentence structure repeatedly?",
        "Can I control longer sentences without losing accuracy?",
      ]),
      p("The important word here is control."),
      p("Using complex grammar isn't enough. You need to use it accurately and appropriately."),

      h("The solution isn't “write harder”"),
      p("If your Writing score has been stuck for months, don't immediately conclude that you aren't capable of improving."),
      p("Instead, change the question."),
      p("Don't ask:"),
      p("“How many essays should I write this week?”", true),
      p("Ask:"),
      p("“What is preventing my writing from moving to the next level?”", true),
      p("Once you identify that barrier, your practice becomes much more purposeful."),
      p("Writing improvement isn't about producing more words. It's about making better decisions with every paragraph, sentence, and idea."),
    ],
  },
  {
    slug: "memorizing-templates",
    category: "Strategy",
    title: "The Problem With Memorizing IELTS Templates",
    excerpt:
      "A template can give you structure. It can't give you a good answer — and relying on one too heavily can hold your writing back.",
    readingTime: "5 min",
    body: [
      p("Templates are attractive."),
      p("They give you a structure when you don't know what to write. They make an unfamiliar question look familiar. And when you're nervous about the exam, having something you can remember can feel reassuring."),
      p("But there's a problem."),
      p("A template can give you structure. It cannot give you a good answer.", true),
      p("And relying too heavily on memorized language can actually hold your IELTS Writing back."),

      h("The illusion of preparation"),
      p("Imagine you memorize an introduction:"),
      p("“In this rapidly changing world, the issue of... has become a topic of considerable debate...”", true),
      p("It sounds academic."),
      p("So you use it in every essay."),
      p("The problem?"),
      p("The sentence may contribute almost nothing to your response."),
      p("It doesn't demonstrate that you've understood the question. It doesn't develop your position. And it may make your writing sound rehearsed rather than natural."),
      p("IELTS isn't testing whether you can reproduce an essay you've prepared beforehand.", true),
      p("It's testing whether you can respond effectively to the task in front of you."),

      h("Structure is useful. Scripts aren't."),
      p("This distinction matters."),
      p("You absolutely should understand how to organize an essay."),
      p("You should know how to:"),
      list([
        "introduce your position,",
        "develop ideas,",
        "use relevant examples,",
        "connect paragraphs,",
        "and reach a clear conclusion.",
      ]),
      p("But there is a big difference between understanding a structure and memorizing sentences."),
      p("Think of it like navigation."),
      p("You need to know where you're going."),
      p("You don't need to memorize every step of the road."),
      p("A flexible structure allows you to adapt your response to different questions."),
      p("A rigid template forces the question into the structure you've already memorized."),

      h("What happens when the question changes?"),
      p("This is where memorized templates often break down."),
      p("Suppose you've prepared a structure for an opinion essay."),
      p("Then you encounter a question that asks you to discuss two views and give your own opinion."),
      p("Your memorized introduction may still work linguistically—but your overall response may not properly address the task."),
      p("The result can be an essay that looks organized while failing to fully answer the question."),
      p("And organization alone doesn't guarantee a high score.", true),

      h("Memorize principles, not paragraphs"),
      p("Instead of memorizing complete sentences, build a small collection of principles."),
      p("For example:"),
      sub("Principle 1: Answer the actual question"),
      p("Before thinking about vocabulary, identify exactly what the question requires."),
      sub("Principle 2: Make your position clear"),
      p("If the task asks for your opinion, your position should be understandable throughout the response."),
      sub("Principle 3: Develop your ideas"),
      p("A point without explanation is often just a claim."),
      p("Ask:"),
      p("Why?"),
      p("How?"),
      p("What does this lead to?"),
      sub("Principle 4: Use examples strategically"),
      p("Examples should support your argument—not simply fill space."),
      sub("Principle 5: Keep your language natural"),
      p("Academic writing doesn't mean making every sentence complicated."),

      h("Confidence comes from flexibility"),
      p("The best preparation isn't being able to write one excellent essay from memory."),
      p("It's being able to sit in front of an unfamiliar question and think:"),
      p("“I haven't seen this exact question before, but I know what to do.”", true),
      p("That's a much stronger kind of confidence."),
      p("Don't memorize the road. Learn how to navigate.", true),
      p("When you understand structure, develop ideas logically, and use language flexibly, you become less dependent on templates—and much more prepared for the actual exam."),
    ],
  },
  {
    slug: "band-7-requires",
    category: "Insights",
    title: "What Band 7 Actually Requires",
    excerpt:
      "Band 7 isn't about harder English. It's about clarity, development, control, and flexibility — consistently.",
    readingTime: "6 min",
    body: [
      p("Band 7 is one of the most common IELTS goals."),
      p("For many students, it represents an important threshold:"),
      list([
        "University admission.",
        "Professional opportunities.",
        "Immigration requirements.",
        "Or simply the feeling that they have reached a genuinely strong level of English.",
      ]),
      p("But what does Band 7 actually mean?"),
      p("And perhaps more importantly:"),
      p("What separates a Band 7 performance from a Band 6?", true),
      p("The answer isn't simply “more difficult English.”"),

      h("Band 7 isn't perfection"),
      p("Let's start with a misconception."),
      p("A Band 7 candidate does not need perfect grammar."),
      p("They don't need to understand every word in the Listening or Reading sections."),
      p("They don't need to sound like a native speaker."),
      p("And they don't need to use complicated vocabulary in every sentence."),
      p("Band 7 is better understood as effective, competent communication with good control and relatively strong consistency.", true),
      p("There can still be mistakes."),
      p("The difference is that the mistakes generally don't prevent you from communicating your ideas effectively."),

      h("In Writing, ideas need development"),
      p("One of the biggest differences between average and stronger writing is not vocabulary."),
      p("It's development.", true),
      p("Consider this:"),
      p("Governments should invest more in public transport because it can reduce traffic.", true),
      p("That's a reasonable point."),
      p("But a stronger response explores the relationship:"),
      p("How can public transport reduce traffic?"),
      p("Why might people choose it?"),
      p("What happens when more people use it?"),
      p("What are the wider consequences?"),
      p("Strong writing doesn't simply collect ideas."),
      p("It takes the reader somewhere.", true),

      h("In Speaking, communication matters more than performance"),
      p("Many candidates try to “sound advanced” during the Speaking test."),
      p("They force complex vocabulary into answers."),
      p("They memorize expressions."),
      p("They try to produce perfect sentences."),
      p("This can make their speech less natural."),
      p("A strong speaker can:"),
      list([
        "answer directly,",
        "extend their ideas,",
        "explain reasons,",
        "give examples,",
        "compare experiences,",
        "clarify their meaning,",
        "and maintain a conversation naturally.",
      ]),
      p("You don't need to turn every answer into a speech."),
      p("You need to communicate clearly and develop your response."),

      h("Vocabulary should serve your meaning"),
      p("Band 7 doesn't mean replacing every common word with a sophisticated synonym."),
      p("Compare:"),
      p("This issue is very important.", true),
      p("with:"),
      p("This issue has significant consequences for young people entering the workforce.", true),
      p("The second sentence isn't better simply because it sounds more complicated."),
      p("It's better because it communicates a more precise idea."),
      p("That is the mindset worth developing."),
      p("Don't ask:"),
      p("“What's the most advanced word I can use?”", true),
      p("Ask:"),
      p("“What's the most precise way to express this idea?”", true),

      h("Consistency matters"),
      p("One excellent paragraph doesn't automatically make a Band 7 performance."),
      p("Your overall performance matters."),
      p("You might produce a very strong Speaking answer and then struggle to maintain fluency later."),
      p("You might write one excellent paragraph but leave another underdeveloped."),
      p("You might know sophisticated vocabulary but use it inconsistently."),
      p("Band 7 requires you to perform reasonably strongly across the relevant criteria, not just produce occasional moments of brilliance.", true),

      h("So, what should you actually aim for?"),
      p("Instead of chasing “advanced English,” focus on four things:"),
      sub("Clarity."),
      p("Can the examiner understand your meaning easily?"),
      sub("Development."),
      p("Can you explain and support your ideas?"),
      sub("Control."),
      p("Can you use grammar and vocabulary accurately enough to communicate effectively?"),
      sub("Flexibility."),
      p("Can you respond to unfamiliar questions instead of relying on memorized answers?"),
      p("That's the real challenge."),
      p("And that's also the good news."),
      p("You don't need to become a completely different English speaker to reach Band 7.", true),
      p("You need to become a more deliberate and effective communicator."),
    ],
  },
  {
    slug: "prepare-without-burnout",
    category: "Mentor Notes",
    title: "How to Prepare for IELTS Without Burning Out",
    excerpt:
      "More hours isn't the same as better preparation. Here's how to focus on what actually moves your score.",
    readingTime: "5 min",
    body: [
      p("IELTS preparation can quietly become exhausting."),
      p("You start with motivation."),
      p("One hour becomes two."),
      p("Two becomes three."),
      p("You download resources, save videos, collect vocabulary lists, write essays, take practice tests—and eventually you realize you're spending more time preparing to prepare than actually improving."),
      p("Then comes the frustration."),
      p("You feel like you're working hard, but you're not sure whether you're moving forward.", true),
      p("This is where a different approach can help."),

      h("You don't need to do everything"),
      p("There is an endless amount of IELTS material available."),
      p("More books."),
      p("More videos."),
      p("More practice questions."),
      p("More vocabulary lists."),
      p("More strategies."),
      p("The availability of resources can create the illusion that successful preparation requires consuming all of them."),
      p("It doesn't."),
      p("You need the right work, not unlimited work.", true),
      p("Your preparation should answer three questions:"),
      list([
        "Where am I now?",
        "Where do I need to go?",
        "What is the biggest gap between those two points?",
      ]),
      p("Without those answers, it's easy to spend your time doing whatever feels productive."),

      h("Focus on your biggest gap"),
      p("Imagine your target is Band 7."),
      p("Your Reading is already strong."),
      p("Your Listening is improving steadily."),
      p("But Writing remains at 6.0."),
      p("Spending another three hours watching Listening strategy videos may feel productive."),
      p("But it isn't necessarily the best use of your time."),
      p("Your biggest improvement opportunity is somewhere else."),
      p("Good preparation isn't about giving every skill equal attention."),
      p("It's about understanding where your effort will have the greatest impact.", true),

      h("Create a sustainable routine"),
      p("You don't need to study for six hours every day."),
      p("A sustainable routine is usually more valuable than an ambitious routine you abandon after a week.", true),
      p("For example:"),
      list([
        "Monday — Writing focus",
        "Tuesday — Speaking and vocabulary",
        "Wednesday — Reading",
        "Thursday — Writing and feedback",
        "Friday — Speaking",
        "Weekend — Review and lighter work",
      ]),
      p("The exact schedule isn't important."),
      p("The principle is."),
      p("Consistency beats intensity when intensity isn't sustainable.", true),

      h("Leave room for reflection"),
      p("One of the most overlooked parts of IELTS preparation is reviewing your own performance."),
      p("After completing something, don't immediately move to the next task."),
      p("Pause."),
      p("Ask:"),
      p("What went well?"),
      p("What keeps going wrong?"),
      p("What should I change next time?"),
      p("That short reflection can be more valuable than simply completing another exercise.", true),
      p("Your goal isn't to build a record of everything you've done."),
      p("Your goal is to build better habits and better decisions."),

      h("Don't let IELTS become your entire life"),
      p("This might sound obvious, but it's worth saying."),
      p("You are preparing for an exam."),
      p("You are not putting your life on hold.", true),
      p("Take breaks."),
      p("Sleep properly."),
      p("Talk to people."),
      p("Exercise."),
      p("Spend time away from English."),
      p("Give your brain space to recover."),
      p("Burnout doesn't prove that you're serious about your goal."),
      p("Sometimes, it simply means your strategy needs to change."),

      h("Preparation should give you confidence—not consume it"),
      p("The best IELTS preparation eventually creates a feeling of:"),
      p("“I know what I'm doing.”", true),
      p("Not:"),
      p("“I need to do more.”", true),
      p("If your preparation constantly makes you feel behind, overwhelmed, or guilty, take a step back."),
      p("Look at your goal."),
      p("Look at your current ability."),
      p("Identify the biggest gap."),
      p("Then decide what actually deserves your attention."),
      p("You don't need to do everything to prepare well. You need to know what matters most—and give it your attention consistently.", true),
      p("Your IELTS journey should move you toward your goal, not leave you exhausted before you get there.", true),
    ],
  },
];

export const getArticle = (slug: string) => articles.find((a) => a.slug === slug);
